apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-frontend

spec:

  replicas: 1
  template:
    spec:
      containers:
        - name: microtodo-frontend
          image: thinkexception.azurecr.io/microtodo-frontend:dev
      
          env:
          - name: BLAZOR_ENVIRONMENT
            value: "Development"
          - name: Dependencies__APIs__TodosApiBaseUrl
            value: https://microtodo-dev-0.westeurope.cloudapp.azure.com/api/todos