- op: replace
  path: /metadata/annotations/cert-manager.io~1issuer
  value: "letsencrypt-staging-http-issuer"

- op: replace
  path: /spec/tls/0/hosts/0
  value: "microtodo-dev-0.westeurope.cloudapp.azure.com"

- op: replace
  path: /spec/rules/0/host
  value: "microtodo-dev-0.westeurope.cloudapp.azure.com"
