apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-todos-api

spec:
  selector:
    matchLabels:
      app: microtodo-todos-api

  replicas: 3

  template:
    metadata:
      labels:
        app: microtodo-todos-api
    spec:
      containers:
      - name: microtodo-todos-api
        image: thinkexception.azurecr.io/microtodo-todosapi:latest
        imagePullPolicy: Always
        env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Production"
          - name: "ConnectionStrings__TodosDbConnectionString"
            value: Server=mssql;Database={0};User Id=sa;Password=1stChangeIt!;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=False
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
