apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-frontend

spec:
  selector:
    matchLabels:
      app: microtodo-frontend
  
  replicas: 3

  template:
    metadata:
      labels:
        app: microtodo-frontend
    
    spec:
      containers:
      - name: microtodo-frontend
        image: thinkexception.azurecr.io/microtodo-frontend:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
            
        ports:
        - containerPort: 80

        env:
          - name: BLAZOR_ENVIRONMENT
            value: "Production"
          - name: Dependencies__APIs__TodosApiBaseUrl
            value: https://microtodo.westeurope.cloudapp.azure.com/api
