apiVersion: apps/v1
kind: Deployment
metadata:
  name: microtodo-frontend-api

spec:

  replicas: 1
  template:
    spec:
      containers:
        - name: microtodo-frontend-api
          image: thinkexception.azurecr.io/microtodo-frontendapi:dev

          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
            - name: "KEYVAULT_URL"
              value: "https://kv-microtodo-dev-0.vault.azure.net/"
            - name: "FeatureFlags__UseTodosService"
              value: "false"
            