# https://github.com/mohsenmottaghi/container-stress/tree/master

apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-stress
  labels:
    app: stress
spec:
  selector:
    matchLabels:
      stress-area: here
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stress-area: here
    spec:
      containers:
      - name: container-stress
        image: thinkexception.azurecr.io/container-stress:latest
        command: ["stress", "--verbose", "--vm", "1", "--vm-bytes", "1500M", "--vm-keep", "--cpu", "1"]
        # command: ["stress", "--verbose", "--cpu", "1"]

        resources:
          limits:
            memory: "1Gi"
            cpu: "1000"
          requests:
            memory: "512Mi"
            cpu: "500m"
