kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: network-loss
spec:
  selector:
    namespaces:
      - default
  mode: all
  action: loss
  duration: 5m
  loss:
    loss: '50'
    correlation: '0'
  direction: to
