kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: podfault-podfailure-microtodo-frontend-api
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: microtodo-frontend-api
  mode: all
  action: pod-failure
  duration: 5m