apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-test-memory-hellokubernetes
spec:
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/name: hello-kubernetes
  stressors:
    memory:
      workers: 4
      size: 3000MiB
      options: ['']
  duration: '1h'