kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: stress-cpu-microtodo-frontend-api 
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: microtodo-frontend-api
  mode: all
  stressors:
    cpu:
      workers: 4
      load: 70
  duration: 5m
